### PR TITLE
One day or day one, you decide

### PR DESCRIPTION
**Pull request by ujjawalD07**
New quote added. Kindly merge it, Thank you:)

### CODE REVIEW

**Comment by theDevSoham** [comment]
There is only an image file in the commit. Please add the code block too with respective image. @ujjawalD07

**Comment by ujjawalD07** [comment]
Done @Mark-42-max . Kindly check it now.

**Comment by theDevSoham** [comment]
One more thing. It's showing conflicts. I guess you'll have to sync your fork with the latest main branch and commit again.

**Comment by ujjawalD07** [comment]
Sorted :) No conflicts. Kindly merge it now. Thanks

**Review by theDevSoham — APPROVED** [review]
Great Job ✨

**Pull request merged**
